##### Protocol related
SERVER_HEADER_SIZE = 31
CLIENT_HEADER_SIZE = 30
CHUNK_SIZE = 1024
VERSION = 3
DEFAULT_PORT = 8080
HOST = '127.0.0.1'
SERVER_ID = 100000000
OTP_LENGTH = 6
INITIAL_ID = 000000000
SERVER_KEYS_PATH = "Keys/Server_Keys"
CLIENTS_KEYS_PATH = "Keys/Clients_Keys"
CLIENT_UNP_HEADER_FMT = '<B I I 19s B H'
SERVER_UNP_HEADER_FMT = '<I I 19s B H'
MAX_CLIENT_MESSAGE_SIZE = 256
MIN_OTP_VAL = 100000
MAX_OTP_VAL = 999999

#### Client Packet Indexes
CLIENT_PUBLIC_KEY_PAYLOAD = 16
ENC_PAYLOAD_INDEX_FROM_CLIENT = 5
PAYLOAD_SIZE_INDEX_FROM_CLIENT = 4
OP_CODE_INDEX_FROM_CLIENT = 3
TIMESTAMP_INDEX_FROM_CLIENT = 2
RECIPIENT_ID_INDEX_FROM_CLIENT = 1
SENDER_ID_INDEX_FROM_CLIENT = 0

#### Server Packet Indexes
PAYLOAD_INDEX_FROM_SERVER = 6
PAYLOAD_SIZE_INDEX_FROM_SERVER = 5
OP_CODE_INDEX_FROM_SERVER = 4
TIMESTAMP_INDEX_FROM_SERVER = 3
RECIPIENT_ID_INDEX_FROM_SERVER = 2
SENDER_ID_INDEX_FROM_SERVER = 1
SERVER_VERSION_INDEX_FROM_SERVER = 0

#### Client request codes
REGISTER = 100
S_PUBLIC_KEY = 101
CLIENT_SEND_MSG_TO_CLIENT = 102
MESSAGE_RECIEVED_CONFIRMATION = 104
GET_RECIPIENT_PUB_KEY = 105
CLIENT_RECONNECT_REQUEST = 106


##### Server response codes
INIT_REGISTRATION_SUCCEEDED = 200
VERIFIED_OTP_PUBLIC_KEY = 201
DELIVERED_MESSAGE = 202
MESSAGE_DELIVERY_CONFIRMATION_TO_SENDER = 203
SEND_CLIENT_PUB_KEY = 204
CLIENT_RECONNECT_APP = 206
DISCONNECT = 222
DONE_OFFLINE_MESSAGES = 255
REGISTRATION_FAIL = 244
GENERAL_ERROR = 244
VERIFY_LATER = [INIT_REGISTRATION_SUCCEEDED, REGISTER, S_PUBLIC_KEY, CLIENT_SEND_MSG_TO_CLIENT]


##### Encryption
RSA_KEY_BITS = 2048
RSA_KEY_SIZE = 256
AES_KEY_SIZE = 32
PUBLIC_KEY = 160
CONTENT_INDEX = 267
NAME_INDEX = 12
IV_LEN = 16
SIGNATURE_SIZE = 256
RSA_PEM = 464
KEY_START = IV_LEN
KEY_END = IV_LEN + RSA_PEM



##### Database fields and values
DB_NAME = "e2ee.db"
USER_NAME_FIELD = 'user_name'
PUBLIC_KEY_FIELD = 'public_key'
LAST_SEEN_FIELD = 'last_seen'
AES_KEY_FIELD = 'aes_key'
CLIENTS_TABLE = 'clients'


### Error codes
CLIENT_IS_REGISTERED = 150
UNVERIFIED_SIGNATURE = 151
NETWORK_ERROR = 0
CLIENT_DISCONNECTED = 1
CLIENT_NOT_EXIST = 2
MESSAGE_PASSED = 3

## COLORS
RED_START = '\033[31m'
COLOR_END = '\033[0m'
GREEN_TEXT_ST = '\033[1m\033[32m'
GREEN_BACKG_ST = '\033[1m\033[42m'
